public with sharing class Constants {
    
    // HTTP Methods
    public static final String HTTP_GET = 'GET';
    public static final String HTTP_POST = 'POST';
    public static final String HTTP_PUT = 'PUT';
    public static final String HTTP_DELETE = 'DELETE';
    public static final String HTTP_PATCH = 'PATCH';

    // HTTP Status Codes
    public static final Integer HTTP_OK = 200;
    public static final Integer HTTP_BAD_REQUEST = 400;
    public static final Integer HTTP_UNAUTHORIZED = 401;
    public static final Integer HTTP_NOT_FOUND = 404;
    public static final Integer HTTP_NOT_ALLOWED = 405;
    public static final Integer HTTP_INTERNAL_SERVER_ERROR = 500;
}